// Select all the card elements and the element that displays the cards left in the deck
let cards = document.querySelectorAll("div#hand span");
let cardsLeft = document.getElementById("cardsLeft");
let deck = [];

// Function to initialize and shuffle a new deck
function newDeck() {
    // Split the contents of the deckStr variable at each occurrence of the "." character
    // Store the substrings generated by the split() method in the deck array
    deck = deckStr.split(/,\s*/);

    // Sort the contents of the deck array using the shuffle() function as the compare function
    shuffle(deck);

    // Deal the initial set of cards
    dealCards();
}

// Shuffle function that randomizes the order of elements in an array
function shuffle(array) {
    array.sort(function (a, b) {
        return 0.5 - Math.random();
    });
}

// Function to deal cards and update the number of cards left
function dealCards() {
    for (let i = 0; i < 5; i++) {
        // If the length of the deck array is 0, call the newDeck() function
        if (deck.length === 0) {
            newDeck();
        }

        // Use the pop() method to remove the last item from the deck array
        // Store the popped item as the text content of the current item in the cards node list
        let card = deck.pop();
        cards[i].textContent = card;
    }

    // Update the cards left count
    cardsLeft.textContent = deck.length;
}

// Event handler for the deal button
document.getElementById("deal").onclick = dealCards;

// Initialize the deck when the page loads
window.onload = newDeck;

// Original deck string with all cards
let deckStr = `Ace of Hearts, King of Hearts, Queen of Hearts, Jack of Hearts,
               10 of Hearts, 9 of Hearts, 8 of Hearts, 7 of Hearts, 6 of Hearts,
               5 of Hearts, 4 of Hearts, 3 of Hearts, 2 of Hearts,
               Ace of Spades, King of Spades, Queen of Spades, Jack of Spades,
               10 of Spades, 9 of Spades, 8 of Spades, 7 of Spades, 6 of Spades,
               5 of Spades, 4 of Spades, 3 of Spades, 2 of Spades,
               Ace of Diamonds, King of Diamonds, Queen of Diamonds, Jack of Diamonds,
               10 of Diamonds, 9 of Diamonds, 8 of Diamonds, 7 of Diamonds, 6 of Diamonds,
               5 of Diamonds, 4 of Diamonds, 3 of Diamonds, 2 of Diamonds,
               Ace of Clubs, King of Clubs, Queen of Clubs, Jack of Clubs,
               10 of Clubs, 9 of Clubs, 8 of Clubs, 7 of Clubs, 6 of Clubs,
               5 of Clubs, 4 of Clubs, 3 of Clubs, 2 of Clubs`;
